### ISSUE TITLE
Rename project?

### ISSUE THREAD

**Issue by evantravers** [evantravers/smz#3]
I was starting to wonder if I should have `simple-markdown-zettelkasten` be a repo explaining the file format, `smz` be this repo with the tool itself, and `smz.vim` be the corresponding vim plugin that uses this.

I _tend_ to overanalyze… but I didn't know if that would be helpful documentation to a random interested stranger who comes this way.

**Comment by pengwynn** [comment]
👍 Makes sense to split the shell and vim parts.

**Comment by evantravers** [comment]
Any feelings about the repo name and potentially the tool name changing @pengwynn? I know smz is a little longer, but I'm likely to alias useful combinations of the tool anyway.

**Comment by pengwynn** [comment]
No strong preference on names. smz and smz.vim work for me.

**Comment by evantravers** [comment]
It's been renamed… you'll probably need to update remotes. 👍

I've created a stub for smz.vim: https://github.com/evantravers/smz.vim
